### ISSUE TITLE
Update qtype niels brock plugin

### ISSUE THREAD

**Issue by AraPraxis** [praxisdigital/moodle-qtype_wq#2]
Niels brock wants a newer version of "Wiris Quizzes Commons question type"

Plugin/Fork: https://morris.praxis.dk/plugin/632

Github/Fork: https://github.com/praxisdigital/moodle-qtype_wq

New update needed on github: https://moodle.org/plugins/pluginversions.php?plugin=qtype_wq

**Comment by frederikmillingpytlick** [comment]
New version with niels brock fix ready

https://morris.praxis.dk/Plugin/Version?id=9188&handler=Edit&pluginId=632
